<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ingredients;

/**
 * IngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Gets Ingredients id's and names
     * @return array
     */
    public function getIngredients()
    {
        return $this->createQueryBuilder('ingredients')
            ->select('ingredients.id, ingredients.name')->getQuery()->getArrayResult();
    }
}
