<?php

namespace AppBundle\Repository;

/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find meals by selected calories
     * @param integer $calories
     * @return array
     */
    public function getMealsByCalories($calories)
    {
        return $this->createQueryBuilder('m')
            ->leftJoin('m.ingredients', 'mi')
            ->addSelect('mi')
            ->leftJoin('mi.ingredientId', 'i')
            ->addSelect('i')
            ->groupBy('m.id')
            ->having('sum(mi.ammount * i.calories) > :lessCalories')
            ->setParameter(':lessCalories', abs($calories-100))
            ->andHaving('sum(mi.ammount * i.calories) < :moreCalories')
          
            ->setParameter(':moreCalories', abs($calories+1000000))

            ->select('m.id, SUM(mi.ammount * i.calories) as calories, m.name')->getQuery()->getArrayResult();
    }

    /**
     * Get single meal info
     */
    public function getMealInfo($id)
    {
        return $this->createQueryBuilder('m')
            ->select('m.id, m.name, m.about, m.howToMake')
            ->where('m.id = :id')
            ->setParameter('id', $id)->getQuery()->getArrayResult();
    }

    /**
     * Get meals by name
     */
    public function getMealsByName($name)
    {
        return $this->createQueryBuilder('m')
            ->select('m.id, m.name, m.about, m.howToMake')
            ->where('UPPER(m.name) LIKE UPPER(:name)')
            ->setParameter('name', '%'.$name.'%')->getQuery()->getArrayResult();
    }
}
