<?php

namespace AppBundle\Repository;

/**
 * MealWithIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealWithIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
