<?php

namespace AppBundle\Repository;

/**
 * MealRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
