<?php

namespace AppBundle\Repository;

/**
 * scheduleDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
