<?php

namespace AppBundle\Repository;

/**
 * UserMealsSchedulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMealsSchedulesRepository extends \Doctrine\ORM\EntityRepository
{

}
