<?php

namespace AppBundle\Repository;

/**
 * UserMealsSchedulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMealsSchedulesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserSchedules() {
        /**@var User $user */
        $user = $this->getUser();

        $em = $this->getDoctrine()->getManager();
        $userSchedules = $em
            ->getRepository(UserMealsSchedules::class)
            ->findBy(['user' => $user->getId()]);

        foreach($userSchedules as $schedules) {

        }
        var_dump($userSchedules);
    }
}
