<?php

namespace AppBundle\Repository;

/**
 * UserMealsSchedulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMealsSchedulesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getScheduleMeals($id) {
        $mealsQuery = $this->createQueryBuilder('userSchedule');
        $mealsQuery
            ->leftJoin('userSchedule.scheduleDays', 'days')
            ->leftJoin('days.meals', 'meals')
            ->where('userSchedule.id = :id')
            ->setParameter('id', $id)
            ->select('meals.mealJson, days.weekDay as week_day');

        return $mealsQuery->getQuery()->getArrayResult();
    }
}
