<?php

namespace AppBundle\Repository;

/**
 * UserBlockedIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBlockedIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
