parameters:
    my_user_provider.class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    my_user_provider:
        class: '%my_user_provider.class%'
        arguments: ['@fos_user.user_manager',{google: google_id}]
